<div class="row">
    <div class="col-lg-12 text-center">
        <div class="section-heading">
            <h2>REQUISITOS DE CERTIFICADO DE PARCIAL DE LICENCIATURA</h2>
        </div>
    </div>
</div>
<div class="row">
	<div class="col-md-12">
		<legend>El interesado:</legend>
		<ul>
			<li>ORIGINAL Y COPIA DE ACTA DE NACIMIENTO ACTUALIZADA 2015 EN ADELANTE (EN CASO DE NO CONTAR EN SU EXPEDIENTE CON COPIA COTEJADA POR SECRETARÍA DE EDUCACIÓN)</li><br>
			<li>ORIGINAL Y COPIA DE CERTIFICADO DE BACHILLERATO (EN CASO DE NO CONTAR EN SU EXPEDIENTE CON COPIA COTEJADA POR SECRETARÍA DE EDUCACIÓN Y OFICIO DE AUTENTICIDAD).</li><br>
			<li>CUATRO FOTOGRAFÍAS TAMAÑO MIÑÓN OVALADAS, FONDO BLANCO DE FRENTE PAPEL MATE, NO INSTANTÁNEAS, NI PAQUETE DE PROMOCIÓN</li><br>
			<li>ESPECIFICACIONES:</li><br>
			<li>MUJERES: ROPA BLANCA SIN OBJETOS PERSONALES, SIN MAQUILLAJE, OREJAS Y FRENTE DESCUBIERTAS.</li><br>
			<li>HOMBRES: ROPA BLANCA, SIN BARBA, OREJAS Y FRENTE DESCUBIERTOS.  </li><br>
			<li>ORIGINAL Y COPIA DE LOS PAGOS ANTE HACIENDA DEL ESTADO POR EL CONCEPTO DE:</li><br>
			<li>LEGALIZACION DE FIRMAS DE DOCTOS. OFICIALES CON FIRMAS DE FUNCIONARIOS PUBLICOS.  ($220.00 ARTÍCULO 21 FRACCIÓN VII)</li><br>
			<li>POR LA EXPEDICION Y LEGALIZACION DE CERTIFICADOS DE ESTUDIOS DE LICENCIATURA TOTAL O PARCIAL. ($380.00 ARTÍCULO 40 FRACC. VIII)</li><br>
			<li>ORIGINAL Y COPIA DE LA CONSTANCIA DE NO ADEUDO DE LA CARRERA.</li><br>
			<li>ORIGINAL Y COPIA DE LA CONSTANCIA DE NO ADEUDO DE BIBLIOTECA.</li><br>
			<li>ORIGINAL Y COPIA DEL RECIBO DE PAGO REALIZADO EN LA INSTITUCION POR TRÁMITE DE DOCUMENTOS. $1000.00</li><br>
		</ul>
		<strong>
			NOTA: A FALTA DE ALGUNO DE ESTOS REQUISITOS NO SE RECIBE TRÁMITE ALGUNO. <br>
		</strong>
	</div>
</div>