<div class="row">
    <div class="col-lg-12 text-center">
        <div class="section-heading">
            <h2>REQUISITOS DE DUPLICADO CERTIFICADO DE MAESTRIA</h2>
        </div>
    </div>
</div>
<div class="row">
	<div class="col-md-12">
		<legend>El interesado:</legend>
		<ul>
			<li>ACTA DE NACIMIENTO DEL 2015, A LA FECHA</li><br>
			<li>CERTIFICADO DE LICENCIATURA </li><br>
			<li>ACTA DE EXAMEN PROFESIONAL DE LICENCIATURA</li><br>
			<li>TITULO   PROFESIONAL    DE          LICENCIATURA</li><br>
			<li>SEIS FOTOGRAFIAS TAMAÑO CREDENCIAL OVALADAS BLANCO Y NEGRO EN PAPEL MATE</li><br>
			<li>ACTA DE NACIMIENTO DEL 2015 A LA FECHA</li><br>
			<li>CEDULA DE LICENCIATURA</li><br>
			<li>SEIS FOTOGRAFIAS TAMAÑO CREDENCIAL OVALADAS BLANCO Y NEGRO EN PAPEL MATE SIN RETOQUE</li><br>
			<li>CONSTANCIA DE NO ADEUDO DE COLEGIATURA Y BIBLIOTECA.</li><br>
			<li>RECIBO DE PAGO AL IESCH POR TRAMITE DE DOCUMENTOS $ 2,500.00.</li><br>
			<li>
				<b>PAGOS ANTE RECAUDACIÓN DE HACIENDA DEL ESTADO</b>
				<ul>
					<li>ARTICULO 40 FRACCIÓN II EXPEDICIÓN DE DUPLICADO DE CERTIFICADOS DE ESTUDIOS DE NIVEL SUPERIOR. $ 60.00</li><br>
					<li>ARTICULO 21 FRACCIÓN VII LEGALIZACIÓN DE FIRMAS DE DOCUMENTOS OFICIALES, CON FIRMAS DE FUNCIONARIOS PUBLICOS. $ 220.00</li><br>
					<li>ARTICULO 39  FRACCIÓN VXVI Inciso ( c ) EXPEDICIÓN Y LEGALIZACIÓN DE CERTIFICADOS DE ESTUDIO NIVEL SUPERIOR EN TODAS SUS MODALIDADES $ 90.00.</li><br>
				</ul>
			</li>
		</ul>
		<strong>
			NOTA: <br>
            MUJERES:  BLUSA BLANCA, SIN MAQUILLAJE, NI ACCESORIOS, OREJAS Y FRENTE DESCUBIERTAS. <br>
            HOMBRES:    SIN     BARBA,   SIN BIGOTE, OREJAS Y FRENTE DESCUBIERTAS. CAMISA BLANCA, CORBATA DE COLOR   CLARO Y SACO COLOR BEIGE, BLANCO O HUESO. <br>
			TODOS LOS DOCUMENTOS DE OTRO ESTADO, DEBERÁN ESTAR CERTIFICADOS POR LA SECRETARÍA DE EDUCACIÓN DEL MISMO ESTADO Y/O OFICIO DE AUTENTIFICACIÓN EXPEDIDO POR LA ESCUELA DE EGRESO. <br>
			TODOS LOS REQUISITOS EN ORIGINAL Y COPIA TAMAÑO CARTA. A FALTA DE ALGUNO DE ÉSTOS  NO SE RECIBIRÁ ELTRAMITE TIEMPO PROBABLE DE LA LIBERACION DEL CERTIFICADO DE ESTUDIOS DE 2  A  3  MESES  CAMBIO,TODOS LOS DOCUMENTOS DE OTRO ESTADO, DEBERÁN ESTAR CERTIFICADOS POR LA SECRETARÍA DE EDUCACIÓN DEL MISMO ESTADO Y/O OFICIO DE AUTENTIFICACIÓN EXPEDIDO POR LA ESCUELA DE EGRESO.
		</strong>
	</div>
</div>