<div class="row">
    <div class="col-lg-12 text-center">
        <div class="section-heading">
            <h2>REQUISITOS DE TITULACIÓN</h2>
        </div>
    </div>
</div>
<div class="row">
	<div class="col-md-12">
		<legend>El interesado:</legend>
		<ul>
			<li>SOLICITUD DE EXPEDICIÓN DE TITULO REQUISITADA.</li><br>
			<li>ACTA DE NACIMIENTO DEL 2015, EN ADELANTE.</li><br>
			<li>CERTIFICADO DE PREPARATORIA O BACHILLERATO LEGALIZADO.</li><br>
			<li>CONSTANCIA DE AUTENTICIDAD DEL CERTIFICADO DE PREPARATORIA O BACHILLERATO.</li><br>
			<li>CERTIFICADO DE LICENCIATURA.</li><br>
			<li>CONSTANCIA DE SERVICIO SOCIAL LIBERADO POR LA SECRETARÍA DE EDUCACIÓN.</li><br>
			<li>CUATRO FOTOGRAFÍAS TAMAÑO DIPLOMA OVALADAS BLANCO Y NEGRO EN PAPEL MATE.</li><br>
			<li>CUATRO FOTOGRAFÍAS TAMAÑO CREDENCIAL OVALADAS BLANCO Y NEGRO EN PAPEL MATE</li><br>
			<li>MUJERES: SIN RETOQUE, ROPA BLANCA, SIN MAQUILLAJE NI ACCESORIOS, OREJAS Y FRENTE DESCUBIERTAS.</li><br>
			<li>HOMBRES: SIN BARBA, SACO COLOR BEIGE, BLANCO O HUESO,  CORBATA COLOR CLARO, OREJAS Y FRENTE DESCUBIERTAS.</li><br>
			<li>ESTUDIOS FOTOGRÁFICOS SUGERIDOS:  FOTO CHIAPAS, FIGUEROA, FOTO MUNDO, TORRES.</li><br>
			<li>REALIZAR 6 PAGOS ANTE HACIENDA DEL ESTADO </li><br>
			<li>PAGO POR LEGALIZACIÓN DE TÍTULOS DE  GRADO. ART. 40 FRACC. III B). $380.00</li><br>
			<li>PAGO POR ELABORACIÓN, EXPEDICIÓN Y REGISTRO DE TÍTULO PROFESIONAL MEDIO SUPERIOR   Y   SUPERIOR  PARTICULARES. ART. 40 FRACC.IV A). $1200.00</li><br>
			<li>2 PAGOS  POR  LEGALIZACIÓN  DE  FIRMAS   DE   DOCUMENTOS  OFICIALES   CON   FIRMAS   DE FUNCIONARIOS  PÚBLICOS. ART. 21 FRACC.VII. $220.00</li><br>
			<li>PAGO POR CERTIFICACIÓN O LEGALIZACIÓN DE ACTAS DE     EXAMEN         PROFESIONAL SUPERIOR. ART. 39 FRACC. XXII B). $220.00 CADA UNO</li><br>
			<li>PAGO POR EXPEDICIÓN   DE   ACTAS   DE EXAMEN     PROFESIONAL     TIPO   MEDIO SUPERIOR Y SUPERIOR.ART 40 FRACC. lll C). $380.00   </li><br>
			<li>RECIBO DE PAGO DE IESCH POR EXAMEN PROFESIONAL, EXAMEN INSTITUCIONAL, EXAMEN CENEVAL, PROMEDIO, 50% MAESTRÍA (IESCH), CURSO DE TITULACIÓN ($12,000) MEDICINA ($13,000), TESIS ($9,800), 50% MAESTRÍA Y/O 100% ESPECIALIDAD (EXTERNA A IESCH) $20,000.</li><br>
			<li>RECIBO DE PAGO DE IESCH POR TESIS PROFESIONAL DE DISEÑO GRAFICO ($9,800.00)</li><br>
			<li>PAG DEL CURSO DE TITULACIÓN (EN SU CASO)</li><br>
			<li>PAGO DE ASESORÍA DE TESIS (EN SU CASO).</li><br>
			<li>RECIBO DE PAGO DE EXAMEN CENEVAL Y/O POR ÁREAS DE CONOCIMIENTO (INSTITUCIONAL).</li><br>
			<li>CONSTANCIA DE NO ADEUDO DE LA CARRERA (NO NECESITA ACTUALIZACIÓN, SIEMPRE Y CUANDO ESTE FIRMADA POR RECTORIA, VICERRECTORIA, DR. JORGE ANTONIO POLA FIGUEROA O MTRO. JESÚS ANTELMO MORALES) CONSTANCIA DE NO ADEUDO DE BIBLIOTECA ACTUALIZADA.</li><br>
			<li>CONSTANCIA DE NO ADEUDO DEL CURSO DE TITULACIÓN. </li><br>
			<li>CONSTANCIA DE NO ADEUDO DE COLEGIATURA DE MAESTRÍA. (NO NECESITA ACTUALIZACION, SIEMPRE Y CUANDO ESTE FIRMADA POR RECTORIA, VICERRECTORIA O DR. JORGE ANTONIO POLA FIGUEROA O MTRO. JESÚS ANTELMO MORALES) CONSTANCIA DE NO ADEUDO DE BIBLIOTECA ATUALIZADA.</li><br>
			<li>(EN SU CASO) CARTA DE NO ADEUDO DE LABORATORIO DE MEDICINA Y QUÍMICO FARMACÉUTICO BIÓLOGO. (ACTUALIZADA)</li><br>
			<li>(EN SU CASO) CONSTANCIA DE LIBERACIÓN DE TESIS O MEMORIA DE CURSO DE TITULACIÓN.</li><br>
			<li>ACREDITACIÓN DE EXAMEN CENEVAL Y/O POR ÁREAS DE CONOCIMIENTO (INSTITUCIONAL).</li><br>
			<li>(EN SU CASO) CERTIFICADO PARCIAL DEL 50% DE MAESTRÍA CURSADA EN OTRA INSTITUCIÓN.</li><br>
			<li>(EN SU CASO) CONSTANCIA DEL 50% DE MAESTRÍA LEGALIZADA CURSADA EN EL IESCH </li><br>
			<li>(EN SU CASO) CERTIFICADO DE TÉRMINO DE UNA ESPECIALIDAD.</li><br>
			<li>(EN SU CASO) POR PROMEDIO GENERAL DE CALIFICACIONES, ANEXAR CONSTANCIA DE PROMEDIO EXPEDIDA POR LA DIRECCIÓN DE LA CARRERA.</li><br>
			<li>CURP (AMPLIACIÓN %100).</li><br>
			<li>REQUISITO DE TESIS Y/O CURSO DE TITULACIÓN: 5 EMPASTADOS.</li><br>
			<li>A PARTIR DE LA GENERACIÓN QUE INGRESO EN EL 2009, CONSTANCIA DE ACREDITACIÓN DE LOS 4 NIVELES DE INGLÉS.</li><br>
			<li>COPIA DE CREDENCIAL DE EGRESADO</li><br>
		</ul>
		<strong>
			NOTA: FAVOR DE NO REALIZAR ESTOS PAGOS EN EL BANCO <br>
			A FALTA DE ALGUNO DE ESTOS REQUISITOS NO SE RECIBE TRÁMITE ALGUNO. <br>
			FOTO ESTUDIOS RECOMENDADOS: FOTOCHIAPAS, NARVÁEZ, TORRES, FOTOMUNDO, LA SALLE Y FIGUEROA.
		</strong>
	</div>
</div>