<div class="row">
    <div class="col-lg-12 text-center">
        <div class="section-heading">
            <h2>REQUISITOS DE DUPLICADO DE CERTIFICADO DE LICENCIATURA Y/O PARCIAL</h2>
        </div>
    </div>
</div>
<div class="row">
	<div class="col-md-12">
		<legend>El interesado:</legend>
		<ul>
			<li>DOS  FOTOGRAFÍAS TAMAÑO MIÑÓN OVALADAS, FONDO BLANCO DE FRENTE, NO INSTANTÁNEAS.</li><br>
			<li>ESPECIFICACIONES:</li><br>
			<li>MUJERES: ROPA BLANCA SIN OBJETOS PERSONALES, SIN MAQUILLAJE, OREJAS Y FRENTE DESCUBIERTAS.</li><br>
			<li>HOMBRES: ROPA BLANCA, SIN BARBA, OREJAS Y FRENTE DESCUBIERTOS.  </li><br>
			<li>ORIGINAL Y COPIA DE LOS PAGOS ANTE HACIENDA DEL ESTADO POR EL CONCEPTO DE:</li><br>
			<li>ARTÍCULO 21 FRACCIÓN VII LEGALIZACION DE FIRMAS DE DOCTOS. OFICIALES, CON FIRMAS DE FUNCIONARIOS. $ 220.00</li><br>
			<li>ARTÍCULO 40 FRACC.IX EXPEDICION DE DUPLICADOS DE CERTIFICADOS DE ESTUDIOS DE LICENCIATURA $220.00</li><br>
			<li>ORIGINAL Y COPIA DEL RECIBO DE PAGO REALIZADO EN LA INSTITUCION POR TRÁMITE DE DOCUMENTOS. $1000.00</li><br>
		</ul>
		<strong>
			NOTA: A FALTA DE ALGUNO DE ESTOS REQUISITOS NO SE RECIBE TRÁMITE ALGUNO.
		</strong>
	</div>
</div>