<div class="row">
    <div class="col-lg-12 text-center">
        <div class="section-heading">
            <h2>REQUISITOS DE TITULACIÓN DE DOCTORADO</h2>
        </div>
    </div>
</div>
<div class="row">
	<div class="col-md-12">
		<legend>El interesado:</legend>
		<ul>
			<li>SOLICITUD DE EXPEDICIÓN DE TÍTULO REQUISITADA.</li><br>
			<li>ACTA DE NACIMIENTO DEL 2015 A LA  FECHA</li><br>
			<li>CERTIFICADO DE MAESTRIA COPIA</li><br>
			<li>CERTIFICADO DE DOCTORADO</li><br>
			<li>COPIA DE CREDENCIAL  DE EGRESADO .</li><br>
			<li>TÍTULO DE MAESTRÍA</li><br>
			<li>CÉDULA DE MAESTRÍA</li><br>
			<li>TRES FOTOGRAFIAS TAMAÑO -CREDENCIAL OVALADAS BLACO Y -NEGRO EN PAPEL MATE Y TRES -TAMAÑO DIPLOMA. ESTUDIOS FOTOGRAFICOS SUGERIDOS: FOTO MUNDO, FOTO CHIAPAS ,FIGUEROA, LA SALLE Y TREJO</li><br>
			<li>MUJERES: SIN RETOQUE, ROPA BLANCA, SIN MAQUILLAJE NI ACCESORIOS, OREJAS Y FRENTE DESCUBIERTAS.</li><br>
			<li>HOMBRES: SIN BARBA, SACO COLOR BEIGE, BLANCO O HUESO,  CORBATA COLOR CLARO, OREJAS Y FRENTE DESCUBIERTAS.</li><br>
			<li>CONSTANCIA DE NO ADEUDO DE COLEGIATURA Y BIBLIOTECA (ACTUALIZADAS)</li><br>
			<li>RECIBO DE PAGO DEL IESCH POR EXAMEN DE GRADO  DE TITULACION POR PROMEDIO(17,000.00).</li><br>
			<li>NO HABER INTERRUMPIDO SUS ESTUDIOS.</li><br>
			<li>NO HABER CURSADO MATERIA LIBRE</li><br>
			<li>PROMEDIO MINIMO DE 9.0</li><br>
			<li>POR TESIS:  PAGO DE ASESORÍA DE TESIS $ 4,800.00</li><br>
			<li>PAGO DE TRÁMITE DE EXAMEN DE GRADO $10,000.00</li><br>
			<li>CD DE LA TESIS.</li><br>
			<li>OFICIO  DE REVISORES DE TESIS</li><br>
			<li>DICTAMEN  DE LIBERACIÓN DE TESIS</li><br>
			<li>5 EMPASTADOS DE TESIS. UN EMPASTADO DEBERÁ CONTENER ORIGINAL DEL DICTAMEN, DE LIBERACION DE TESIS.</li><br>
			<li>
				<b>PAGOS ANTE RECAUDACIÓN DE HACIENDA DEL ESTADO</b>
				<ul>
					<li>PAGO POR  EXPEDICIÓN  DE ACTAS DE GRADO (ART. 39 FRAC. VIII)  $410.00</li><br>
					<li>PAGO POR LEGALIZACIÓN DE DOCUMENTOS DE GRADO, CERTIFICACIÓN O LEGALIZACIOÓN  DE ACTAS DE EXAMEN PROFESIONAL ( CERTIFICACIÓN O LEGALIZACIÓN DE ACTAS DE EXAMEN PROFESIONAL ( ART. 39 FRAC. XXII INCISO. B) $ 220.00</li><br>
					<li>PAGOS POR LEGALIZACIÓN DE FIRMAS DE DOCUMENTOS OFICIALES CON FIRMAS DE                                                                                 FUNCIONARIOS PÚBLICOS, (ART. 21  FRACC. VII ) $220.00</li><br>
					<li>PAGOS POR LEGALIZACIÓN DE FIRMAS DE DOCUMENTOS OFICIALES CON FIRMAS  DE                                                                                 FUNCIONARIOS PÚBLICOS, (ART. 21  FRACC. VII ) $220.00</li><br>
					<li>PAGO  POR LEGALIZACIÓN DE TÍTULO DE GRADO. (ART. 40 FRACC. III INCISO B)  $380.00</li><br>
					<li>PAGO POR ELABORACIÓN, EXPEDICIÓN Y REGISTRO DE TITULO PROFESIONAL MEDIO SUPERIOR Y SUPERIOR PARTICULARES. ART. 40 FRACC. IV INCISO A   $1,200.00</li><br>
				</ul>
			</li>
		</ul>
		<strong>
			NOTA: <br>
			ESTUDIOS REALIZADO EN OTRO ESTADO DEBERAN TRAER LA LEGALIZACION O CONSTANCIA DE AUTENTIFICACION DE SU ESTADO. <br>
			TODOS LOS  DOCUMENTOS EN ORIGINAL Y UNA COPIA  TAMAÑO CARTA. A FALTA DE ALGUNO DE ESTOS NO  SE  RECIBIRÁ EL TRÁMITE TIEMPO PROBABLE DE LA LIBERACION DEL GRADO SERA DE 3 A 4 MESES
		</strong>
	</div>
</div>