<div class="row">
    <div class="col-lg-12 text-center">
        <div class="section-heading">
            <h2>REQUISITOS DE TITULACIÓN DE MAESTRÍA</h2>
        </div>
    </div>
</div>
<div class="row">
	<div class="col-md-12">
		<legend>El interesado:</legend>
		<ul>
			<li>SOLICITUD DE EXPEDICIÓN DE TÍTULO REQUISITADA</li><br>
			<li>ACTA DE NACIMIENTO DEL 2015, EN ADELANTE, ORIGINAL Y COPIA.</li><br>
			<li>COPIA  DE CREDENCIAL DE EGRESADO.</li><br>
			<li>COPIA DEL CERTIFICADO DE LICENCIATURA.</li><br>
			<li>CERTIFICADO DE MAESTRÍA ORIGINAL Y COPIA.</li><br>
			<li>TÍTULO   PROFESIONAL DE  -LICENCIATURA , ORIGINAL Y COPIA .</li><br>
			<li>CEDULA PROFESIONAL   DE   -LICENCIATURA. ORIGINAL Y COPIA.</li><br>
			<li>TRES FOTOGRAFIAS TAMAÑO -CREDENCIAL OVALADAS BLANCO Y -NEGRO EN PAPEL MATE Y TRES -TAMAÑO DIPLOMA.</li><br>
			<li>CONSTANCIA DE NO ADEUDO DE COLEGIATURA Y BIBLIOTECA. (ACTUALIZADAS).</li><br>
			<li>RECIBO DE PAGO AL IESCH POR EXAMEN DE GRADO.  ORIGINAL Y COPIA. $15, 000.00</li><br>
			<li>PAGO DE ASESORIA DE TESIS  (EN SU CASO). ($4,600.00)</li><br>
			<li>TRÁMITE DE EXAMEN DE GRADO VÍA TESIS ($9,000.00)</li><br>
			<li>CD DEL TRABAJO DE TESIS</li><br>
			<li>LIBERACIÓN DE REVISORES DE TESIS</li><br>
			<li>CONSTANCIA DE LIBERACIÓN DE TESIS, FIRMADA POR EL DIRECTOR DE POSGRADO.</li><br>
			<li> 5 EMPASTADOS DE TESIS. UN ENPASTADO DE TESIS DEBERÁ        CONTENER  EL ORIGINAL DE LIBERACIÓN  LA MISMA.</li><br>
			<li>CONSTANCIA DEL 50% DE CREDITOS DE DOCTORADO LEGALIZADA POR LA SECRETARÍA DE EDUCACIÓN SIEMPRE Y CUANDO SEA CURSADA EN EL IESCH. PARA CURSAMIENTO EN  OTRA INSTITUCIÓN DEBERA PRESENTAR CERTIFICADO PARCIAL DE ESTUDIOS LEGALIZADO.</li><br>
			<li>
				<b>PAGOS ANTE RECAUDACIÓN DE HACIENDA DEL ESTADO</b>
				<ul>
					<li>PAGO POR  EXPEDICIÓN  DE ACTAS DE -GRADO (ART. 39 FRAC. VIII)  $410.00</li><br>
					<li>PAGO POR LEGALIZACIÓN DE DOCUMENTOS DE GRADO, CERTIFICACION O LEGALIZACIÓN  DE ACTAS DE EXAMEN PROFESIONAL  ART. 39 FRAC. XXII INCISO. B) $ 220.00</li><br>
					<li>2 PAGOS POR LEGALIZACIÓN DE FIRMAS DE DOCUMENTOS OFICIALES CON FIRMAS  DE FUNCIONARIOS PÚBLICOS, (ART. 21  FRACC. VII ) $220.00</li><br>
					<li>PAGO  POR LEGALIZACIÓN DE TÍTULO DE GRADO. (ART. 40 FRACC. III INCISO B)  $380.00</li><br>
					<li>PAGO POR ELABORACIÓN, EXPEDICIÓN Y REGISTRO DE TÍTULO PROFESIONAL MEDIO SUPERIOR Y SUPERIOR PARTICULARES. (ART. 40 FRACC. IV INCISO A  ) $1,200.00</li><br>
				</ul>
			</li>
		</ul>
		<strong>
			NOTA: <br>
            MUJERES:  BLUSA BLANCA, SIN MAQUILLAJE, NI ACCESORIOS, OREJAS Y FRENTE DESCUBIERTAS. <br>
            HOMBRES:    SIN     BARBA,   SIN BIGOTE, OREJAS Y FRENTE DESCUBIERTAS. CAMISA BLANCA, CORBATA DE COLOR   CLARO Y SACO COLOR BEIGE, BLANCO O HUESO. <br>
            *PROGRAMACIÓN MENSUAL:  RECEPCIÓN DE DOCUMENTO UN MES ANTES DE LA TOMA DE PROTESTA, LA ÚLTIMA FECHA DE  RECEPCIÓN SERÁ EN EL  MES DE OCTUBRE . <br>
			TODOS LOS DOCUMENTOS DE OTRO ESTADO DEBERÁN ESTAR LEGALIZADOS POR LA SECRETARÍA DE EDUCACIÓN, A FALTA DE ALGUNO DE ESTOS REQUISITOS NO SE  RECIBIRÁ EL TRÁMITE. TIEMPO PROBABLE DE LA LIBERACIÓN DEL TÍTULO DE 2 A 3 MESES		</strong>
	</div>
</div>