<div class="row">
    <div class="col-lg-12 text-center">
        <div class="section-heading">
            <h2>REQUISITOS PARA LA CERTIFICACIÓN DE ACTA DE POSGRADO (DUPLICADO)</h2>
        </div>
    </div>
</div>
<div class="row">
	<div class="col-md-12">
		<legend>El interesado:</legend>
		<ul>
			<li>BOLETA DE PAGO DE IESCH POR CONCEPTO DE CERTIFICACIÓN DE ACTA DE EXAMEN DE POSGRADO $2,000.00.</li><br>
			<li>ACTA DE NACIMIENTO (2015), EN ADELANTE</li><br>
			<li>COPIA DEL ACTA DE EXAMEN DE POSGRADO (ANTERIOR)</li><br>
			<li>DOS FOTOGRAFIAS TAMAÑO MIÑON O CREDENCIAL OVALADAS BLANCO Y NEGRO PAPEL MATE.</li><br>
			<li>a) MUJERES (FAVOR DE PEDIRLA SIN RETOQUE, ROPA BLANCA, SIN MAQUILLAJE NI ACCESORIOS).</li><br>
			<li>b) HOMBRES (SIN BARBA, SACO COLOR BEIGE, BLANCO O HUESO, CORBATA COLOR CLARO).</li><br>
			<li>
				<b>PAGOS ANTE RECAUDACIÓN DE HACIENDA DEL ESTADO</b>
				<ul>
					<li>2 PAGOS POR CERTIFICACIÓN O LEGALIZACIÓN DE ACTAS DE EXAMEN PROFESIONAL SUPERIOR.   (ART. 39 FRACC. XXII INCISO B) $ 220.00</li><br>
					<li>1 PAGO POR LEGALIZACIÓN DE FIRMAS DE DOCUMENTOS OFICIALES CON FIRMAS DE FUNCIONARIOS PÚBLICOS. (ART 21 FRACC. VII).  $220.00</li><br>
				</ul>
			</li>
		</ul>
		<strong>
			NOTA: <br>
			TODO LOS REQUISITOS EN ORIGINAL Y UNA COPIA.
		</strong>
	</div>
</div>