<div class="row">
    <div class="col-lg-12 text-center">
        <div class="section-heading">
            <h2>REQUISITOS DE CERTIFICADO DE DOCTORADO</h2>
        </div>
    </div>
</div>
<div class="row">
	<div class="col-md-12">
		<legend>El interesado:</legend>
		<ul>
			<li>ACTA DE NACIMIENTO DEL 2015, A LA FECHA</li><br>
			<li>CERTIFICADO DE MAESTRÍA </li> <br>
			<li>ACTA DE EXAMEN PROFESIONAL DE MAESTRÍA</li> <br>
			<li>TITULO   PROFESIONAL    DE    MAESTRÍA</li> <br>
			<li>SEIS FOTOGRAFIAS TAMAÑO CREDENCIAL OVALADAS BLANCO Y NEGRO EN PAPEL MATE </li> <br>
			<li>ACTA DE NACIMIENTO DEL 2015, A LA FECHA</li> <br>
			<li>CEDULA DE MAESTRÍA</li> <br>
			<li>SEIS FOTOGRAFIAS TAMAÑO CREDENCIAL OVALADAS BLANCO Y NEGRO EN PAPEL MATE SIN RETOQUE</li> <br>
			<li>CONSTANCIA DE NO ADEUDO DE COLEGIATURA Y BIBLIOTECA. </li> <br>
			<li>RECIBO DE PAGO AL IESCH POR TRAMITE DE DOCUMENTOS $ 4,000.00 </li> <br>
			<li>
				<b>PAGOS ANTE RECAUDACIÓN DE HACIENDA DEL ESTADO</b>
				<ul>
					<li>ARTICULO 39  FRACCIÓN XVI inciso (  c  ) EXPEDICIÓN Y LEGALIZACIÓN DE CERTIFICADOS DE ESTUDIO NIVEL SUPERIOR EN TODAS SUS MODALIDADES. $ 90.00</li><br>
					<li>ARTICULO 40 FRACCIÓN III    inciso ( a  )CERTIFICADOS DE GRADO $ 380.00</li><br>
					<li>ARTICULO 21 FRACCIÓN VII LEGALIZACIÓN DE FIRMA DE   DOCUMENTOS OFICIALES, CON FIRMAS DE FUNCIONARIOS PÚBLICOS. $ 220.00</li><br>
				</ul>
			</li>
		</ul>
		<strong>
			NOTA: <br>
            MUJERES:  BLUSA BLANCA, SIN MAQUILLAJE, NI ACCESORIOS, OREJAS Y FRENTE DESCUBIERTAS. <br>
            HOMBRES:    SIN     BARBA,   SIN BIGOTE, OREJAS Y FRENTE DESCUBIERTAS. CAMISA BLANCA, CORBATA DE COLOR   CLARO Y SACO COLOR BEIGE, BLANCO O HUESO. <br>
            TODOS LOS  REQUISITOS EN ORIGINAL Y COPIA TAMAÑO CARTA A FALTA DE ALGUNO DE ÉSTOS  NO SE RECIBIRÁ ELTRAMITE TIEMPO PROBABLE DE LA LIBERACION DEL CERTIFICADO DE ESTUDIOS DE  2 A   3 MESES SUJETO A CAMBIO,TODOS LOS DOCUMENTOS DE OTRO ESTADO, DEBERÁN ESTAR CERTIFICADOS POR LA SECRETARÍA DE EDUCACIÓN DEL MISMO ESTADO Y/O OFICIO DE AUTENTIFICACIÓN EXPEDIDO POR LA ESCUELA DE EGRESO.
		</strong>
	</div>
</div>